apiVersion: v2
name: vsftpd
description: A Helm chart for running vsftpd in Kubernetes
type: application
version: 0.3.3
appVersion: "3.0.5"
icon: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTI4IiBoZWlnaHQ9IjEyOCIgdmlld0JveD0iMCAwIDEyOCAxMjgiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHN0eWxlPi5zdDB7ZmlsbDojNEE5MEUyO30uc3Qxe2ZpbGw6bm9uZTtzdHJva2U6I0ZGRkZGRjtzdHJva2Utd2lkdGg6ODtzdHJva2UtbGluZWNhcDpyb3VuZDtzdHJva2UtbGluZWpvaW46cm91bmQ7fTwvc3R5bGU+PHBhdGggY2xhc3M9InN0MCIgZD0iTTExMiwzNi41djU1YzAchildNodes6LjktNS42LDEyLjUtMTIuNSwxMi41SDI4LjVjLTYuOSwwLTEyLjUtNS42LTEyLjUtMTIuNXYtNzBDMTYsMjcuNiwyMS42LDIyLDI4LjUsMjJoMjMgTDY0LDM2LjVIMTEyeiIvPjxwb2x5bGluZSBjbGFzcz0ic3QxIiBwb2ludHM9IjUwLDYwIDQwLDcwIDUwLDgwIi8+PHBvbHlsaW5lIGNsYXNzPSJzdDEiIHBvaW50cz0iNzgsNjAgODgsNzAgNzgsODAiLz48bGluZSBjbGFzcz0ic3QxIiB4MT0iNDIiIHkxPSI3MCIgeDI9Ijg2IiB5Mj0iNzAiLz48L3N2Zz4=
